server:
  port: 10031

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:mysql://192.168.1.118:3306/demo-springboot-mybatis-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    url: jdbc:p6spy:mysql://192.168.1.118:3306/demo-springboot-mybatis-plus?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1qa@WS

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)