server:
  port: 10031
  
spring:
  elasticsearch:
    rest:
      uris: http://192.168.1.116:9200
  data:
    elasticsearch:
#      cluster-name: es-cluster
      cluster-nodes: 192.168.1.116:9300

initial-import:
  enabled: true